[package]
name = "benches"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = "0.3"
hextile = { path = "../" }
# TODO get rid of need for users to add image crate
image = "0.23"
serde_derive = "1.0"

[[bench]]
name = "bench"
harness = false